
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';

export const RESET_POSTS_REQUEST = 'RESET_POSTS_REQUEST';
export const RESET_POSTS_SUCCESS = 'RESET_POSTS_SUCCESS';
export const RESET_POSTS_FAIL = 'RESET_POSTS_FAIL';

export const POST_RATE_SUCCESS = 'POST_RATE_SUCCESS';
export const POST_RATE_FAIL = 'POST_RATE_FAIL';

